### PR TITLE
refactor things, add interactive commands

### PR DESCRIPTION
**Pull request by a13**

### CODE REVIEW

**Comment by mathiasdahl** [comment]
Thanks @a13 for helping out!

**Comment by mathiasdahl** [comment]
I noticed now that "named" output does not work anymore, at least not with my setup (Git Bash under Windows).

**Comment by a13** [comment]
@mathiasdahl 

sorry, I can't reproduce it, still working fine for me, I used these examples

```bash
$ cat foo
hello
hi
hey

$ grep e _a
hello
hey
```

**Comment by mathiasdahl** [comment]
This is how it works for me:

```
mathias@penguin:~$ echo foo > foo
mathias@penguin:~$ cat foo
foo                                               <--- Correct
mathias@penguin:~$ cat _
foo                                               <--- Correct
mathias@penguin:~$ cat _a
foo                                               <--- Correct
mathias@penguin:~$ echo hello
hello                                           <--- Correct :)
mathias@penguin:~$ cat _
hello                                           <--- Correct
mathias@penguin:~$ cat _a
hello                                           <--- Not correct, it should have output "foo", which was saved as a named output earlier
```

It's probably a small mistake because the code still looks like it should handle the named output scenario.

I will try to hunt it down. Let me know if you find it before me.

**Comment by mathiasdahl** [comment]
The problem is in shell-underscore--maybe-make-temp-file. Probably there has been a misunderstanding of the intent of the named output feature. The intent is for it to be persistent forever unless you overwrite it by adding ! at the end (or delete the file named shell-output-X, where X is the name).

**Comment by a13** [comment]
@mathiasdahl seems fixed in #3

**Comment by mathiasdahl** [comment]
> @mathiasdahl seems fixed in #3

Seems so, thanks! :)

Since you took the trouble of contributing changes I gather you like the idea or at least found it interesting enough. Any thoughts or comments you want to share on the feature, the use of it or further ideas?

**Comment by a13** [comment]
sure :)

I'd like to be able to store not only the result of command execution, but the command line itself (and maybe even some more metainfo).
One of the solutions could be storing all these in a sqlite (for example) db, but to simplify things, I suppose file system should work too.
In this case we would generate not temp files, but directories containing both command line (as a shell of choice script) and the result (and the env, probably).
Thus, we could have a verbose completing-read (counsel/helm/consult+marginalia) interface to the whole shell history, containing a reproducible environment and a reference result.

Besides that, some kind of transient integration could be cool too (I don't have any details here yet, though)

**Comment by mathiasdahl** [comment]
Hi again, sorry for the late reply. Not used to communicating via GH...

There's some deep stuff there! :) It almost sounds like what people are doing in Org Babel and those Python semi-interactive workbooks, but the other way around.

**Pull request merged**
